[tokens]
discord = ""

# TheCatAPI Token (Grab one at thecatapi.com)
catapi = ""

# Sentry Logging
sentry = ""

# PostgreSQL Connection
[tokens.postgres]
host = ""
port = ""
user = ""
password = ""
database = ""
# Redis Connection
[tokens.redis]
host = ""
port = ""
password = ""
db = 1


[git]
# Guild IDs that have access to use git commands.
whitelisted_guilds = [527887739178188830,
                      540978015811928075]

[git.github]
username = ""
repository_name = ""
key = "" # Personal Access Token

[git.gitlab]
instance = "https://gitlab.com" # Gitlab instance url
key = "" # Personal Access Token
project_id = ""

[logging]
# Any bot errors either command errors or internal errors. Should be a webhook url
bot_errors = ""

# Errors that pertain to the timer system. Expecting a webhook url
timer_errors = ""

# Webhook URL
auto_blacklist = ""

# Logging for guild additions and removals
guild_alerts = ""


[bot]
# Bot description
description = ""
# This is by IDs
managers = []
spam_count = 5
# Startup game
game = "rewrite is the future!"

# Set to true if you want commands to be used on_message_edit
edit_commands = true # bool

# Support server invite
support_server_invite = "https://discord.gg/SpFjsy3"

# User-Agent
user_agent = ""

# Guild IDs to use emojis from for the nitro emoji command
nitro_emoji_guilds = []

disabled_cogs = []

[memes]
lmao = "Sorry, what were we laughing about again? ðŸ˜‚ðŸ˜‚ðŸ˜‚"
police = "https://garfield-is-a.lasagna.cat/i/75k9.png"
star = "https://i.imgur.com/vUrBPZr.png"
git = "https://i.imgur.com/SyuscgW.png"
cat = "https://i.imgur.com/dCXyOfK.png"
givedsicoin = "Gave 5 DSicoin"

[memes.non-grouped]
# Commands that aren't registered under the meme group command.

[memes.non-grouped.hidden]
# Commands that are hidden.