[tokens]
discord = ""

# Sentry.io logging
sentry = ""

# PostgreSQL Connection
[tokens.postgres]
uri = "postgres://lightning:postgres@postgres/postgres"

# Redis Connection
[tokens.redis]
host = "redis"
port = "6379"
password = ""
db = 1

[tokens.api]
url = "http://api:8000"
key = "some-key"

[logging]
# Any bot errors either command errors or internal errors. Should be a webhook url
bot_errors = ""

# Webhook URL
blacklist_alerts = ""

# Logging for guild additions and removals
guild_alerts = ""

# Logging Level (defaults to INFO if not set)
level = ""

# Console logger handler
console = true


[bot]
spam_count = 5
# Startup game
game = "rewrite is the future!"

# Prometheus plugin is disabled by default, remove it from the list below if you want to enable it
disabled_cogs = ['lightning.cogs.prometheus']

# Support server invite
support_server_invite = "https://discord.gg/SpFjsy3"
